### ISSUE TITLE
How to audit user roles

### ISSUE THREAD

**Issue by braianj** [sonata-project/EntityAuditBundle#295]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no

Hello, I was able to implement part of the code, and add into config.yml

``` yml
simple_things_entity_audit:
    global_ignore_columns:
        - ts
        - tu
        - salt
        - password
    audited_entities:
        - LoginBundle\Entity\Users
        - LoginBundle\Entity\Roles
```
But I can't  audit the table users_roles, since there is no entity for that table.
Inside Users entity I have this

 ``` php
   /**
     * @var \Doctrine\Common\Collections\Collection
     *
     * @ORM\ManyToMany(targetEntity="LoginBundle\Entity\Roles", inversedBy="users")
     * @ORM\JoinTable(name="users_roles",
     *   joinColumns={
     *     @ORM\JoinColumn(name="id_user", referencedColumnName="id")
     *   },
     *   inverseJoinColumns={
     *     @ORM\JoinColumn(name="id_rol", referencedColumnName="id")
     *   }
     * )
     */
    private $roles;

    public function __construct()
    {
        $this->roles = new \Doctrine\Common\Collections\ArrayCollection();
    }
```

And inside roles

   ``` php
 /**
     * @var \Doctrine\Common\Collections\Collection
     *
     * @ORM\ManyToMany(targetEntity="LoginBundle\Entity\Users", mappedBy="roles")
     */
    private $users;
```

And then it will be usefull to know how to user the templates already created by this repo.

Best
