### ISSUE TITLE
Audit tables are being generated for all entities, not just the ones specified in config

### ISSUE THREAD

**Issue by alexandrubau** [sonata-project/EntityAuditBundle#370]
The command `php bin/console d:s:u --dump-sql` dumps an SQL that would generate audit tables for all entities in my project even though I specified only one entity in config.

```yaml
simple_things_entity_audit:
  audited_entities:
    - App\Entity\Page
``` 

In [docs](https://sonata-project.org/bundles/doctrine-orm-admin/3-x/doc/reference/audit.html) it says that a `force.audit` option would disable audit for all entities but that option does not exist. 

Using `sonata-project/EntityAuditBundle` v1.1.0
