### ISSUE TITLE
Ignore related tables for auditiong 

### ISSUE THREAD

**Issue by dmitrach** [sonata-project/EntityAuditBundle#601]
## Feature Request
I would like to ignore a related table with M:M for auditing.

Actually it is not possible as I see and I cannot change the current library.  

https://stackoverflow.com/questions/77801195/how-to-ignore-many-to-many-relationship-with-entityaudit-entityauditbundle?noredirect=1#comment137179292_77801195 

```php
<?php
/** @Entity **/
class User
{
    // ...

    /**
     * @ManyToMany(targetEntity="User", mappedBy="myFriends")
     **/
    private $friendsWithMe;

    /**
     * @ManyToMany(targetEntity="User", inversedBy="friendsWithMe")
     * @JoinTable(name="friends",
     *      joinColumns={@JoinColumn(name="user_id", referencedColumnName="id")},
     *      inverseJoinColumns={@JoinColumn(name="friend_user_id", referencedColumnName="id")}
     *      )
     **/
    private $myFriends;

    public function __construct() {
        $this->friendsWithMe = new \Doctrine\Common\Collections\ArrayCollection();
        $this->myFriends = new \Doctrine\Common\Collections\ArrayCollection();
    }

    // ...
}
```

```
simple_things_entity_audit:
    audited_entities:
        - App\Entity\User
        - 
    global_ignore_tables:
        - friends
```

Thanks.

**Comment by shepherdmat** [comment]
How about instead of excluding individual tables, add an option to skip relationships.
```
simple_things_entity_audit:
    disable_associations: true
    audited_entities:
        - App\Entity\User
```
